# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-05-17 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0035_add_imscp_preset'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelmetadata',
            name='local_only',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contentnode',
            name='local_only',
            field=models.NullBooleanField(default=False),
        ),
    ]
